#!/usr/bin/env python
import subprocess
import string
import httplib, urllib
import requests
import json

#Configuration
RECOMMENDER_URL = "http://localhost:8080"
PROJECT_ID = 1

proc = subprocess.Popen(["git diff --name-only HEAD HEAD~1"], stdout=subprocess.PIPE, shell=True)
(out, err) = proc.communicate()
files=string.split(out, '\n')
del files[-1]

url = RECOMMENDER_URL + "/recommend"
payload = {'projectId' : PROJECT_ID, "filePaths": files}
headers = {'Content-type': 'application/json'}
r = requests.post(url, data=json.dumps(payload), headers=headers)
print "Here is the recommended reviewers for ur commit:"
reviewers = r.json()

for reviewer in reviewers:
    print reviewer['name']